In [103]:
import numpy as np

directions = [
  (-1,  0),
  ( 0, -1),
  ( 1,  0),
  ( 0,  1),
]

grid = np.zeros((5, 5), dtype=int)
color = 0
solution = None
end = False

def concat_grid():
  result = ''
  for index, row in enumerate(grid):
    for item in row:
      result += str(item)
    if index != 4:
      result += '\n'
  return result

# pure
def find_first_empty(grid):
  for x, row in enumerate(grid):
    for y, item in enumerate(row):
      if item == 0:
        return x, y
  
  return None

def check_solution(grid, region):
  districts_won = 0
  for color in range(1, 6):
    sum = 0
    for x, row in enumerate(grid):
      for y, item in enumerate(row):
        if item == color and region[x][y] == 'O':
          sum += 1
    if sum >= 3:
      districts_won += 1
  return districts_won >= 3

# algo
def gerrymander(raw):
  global grid
  global color
  global solution
  global end

  grid = np.zeros((5, 5), dtype=int)
  color = 0
  solution = None
  end = False

  region = raw.split('\n')
    
  def calc(region):
    global color

    def depth_first(coords, depth):
      global end
      global solution
      x, y = coords
      if end: return

      grid[x][y] = color

      if depth == 5:
        if color != 5:
          calc(region)
        else:
          print(grid)
          if check_solution(grid, region):
            solution = concat_grid()
            end = True
      else:
        for dx, dy in directions:
          if (0 <= x + dx) and \
              (x + dx < 5) and \
              (0 <= y + dy) and \
              (y + dy < 5) and \
              grid[x + dx][y + dy] == 0:
            depth_first((x + dx, y + dy), depth + 1)

      grid[x][y] = 0

    coords = find_first_empty(grid)
    if coords is not None:
      color += 1
      depth_first(coords, 1)
      color -= 1
    
    return solution
  
  return calc(region)


region = [
            'OXOOX',
            'XXOXO',
            'XOXXX',
            'XXOXX',
            'OXXOO']

print(gerrymander('\n'.join(region)))



[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 4]
 [1 2 3 4 4]
 [1 2 3 4 5]
 [1 2 3 5 5]
 [1 2 3 5 5]]
[[1 2 3 4 4]
 [1 2 3 4 4]
 [1 2 3 4 5]
 [1 2 3 5 5]
 [1 2 3 5 5]]
[[1 2 3 4 4]
 [1 2 3 5 4]
 [1 2 3 5 4]
 [1 2 3 5 4]
 [1 2 3 5 5]]
[[1 2 3 4 4]
 [1 2 3 4 4]
 [1 2 3 4 5]
 [1 2 3 3 5]
 [1 2 5 5 5]]
[[1 2 3 3 3]
 [1 2 3 3 4]
 [1 2 4 4 4]
 [1 2 4 5 5]
 [1 2 5 5 5]]
[[1 2 3 3 3]
 [1 2 3 3 4]
 [1 2 5 4 4]
 [1 2 5 4 4]
 [1 2 5 5 5]]
[[1 2 3 3 3]
 [1 2 3 3 4]
 [1 2 5 4 4]
 [1 2 5 4 4]
 [1 2 5 5 5]]
[[1 2 3 3 3]
 [1 2 3 3 4]
 [1 2 5 5 4]
 [1 2 5 5 4]
 [1 2 5 4 4]]
[[1 2 3 4 4]
 [1 2 3 3 4]
 [1 2 5 3 4]
 [1 2 5 3 4]
 [1 2 5 5 5]]
[[1 2 3 3 4]
 [1 2 3 3 4]
 [1 2 3 4 4]
 [1 2 5 4 5]
 [1 2 5 5 5]]
[[1 2 3 3 4]
 [1 2 3 3 4]
 [1 2 3 5 4]
 [1 2 5 5 4]
 [1 2 5 5 4]]
[[1 2 3 3 4]
 [1 2 3 3 4]
 [1 2 3 5 4]
 [1 2 5 5 4]
 [1 2 5 5 4]]
[[1 2 3 3 4]
 [1 2 5 3 4]
 [1 2 5 3 4]
 [1 2 5 3 4]
 [1 2 5 5 4]]
[[1 2 3 3 3]
 [1 2 4 3 3]
 [1 2 4 4 5]
 [1 2 4 4 5]
 [1 2 5 5 5]]
[[1 2 3 3 